In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.externals import joblib

In [84]:
data = pd.read_csv("D:/ML_Work/Wine Quality/data_sep.csv")

In [85]:
data.head()

Wine_ID  fixed acidity  volatile acidity  citric acid  residual sugar  \
0        0            7.4              0.70         0.00             1.9   
1        1            7.8              0.88         0.00             2.6   
2        2            7.8              0.76         0.04             2.3   
3        3           11.2              0.28         0.56             1.9   
4        4            7.4              0.70         0.00             1.9   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [83]:
data = pd.read_csv(dataset_url, sep=';')
data.to_csv("data_sep.csv", index=True)

In [86]:
data.head()

Wine_ID  fixed acidity  volatile acidity  citric acid  residual sugar  \
0        0            7.4              0.70         0.00             1.9   
1        1            7.8              0.88         0.00             2.6   
2        2            7.8              0.76         0.04             2.3   
3        3           11.2              0.28         0.56             1.9   
4        4            7.4              0.70         0.00             1.9   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [87]:
data.shape

(1599, 13)

In [88]:
data.describe()

Wine_ID  fixed acidity  volatile acidity  citric acid  \
count  1599.000000    1599.000000       1599.000000  1599.000000   
mean    799.000000       8.319637          0.527821     0.270976   
std     461.735855       1.741096          0.179060     0.194801   
min       0.000000       4.600000          0.120000     0.000000   
25%     399.500000       7.100000          0.390000     0.090000   
50%     799.000000       7.900000          0.520000     0.260000   
75%    1198.500000       9.200000          0.640000     0.420000   
max    1598.000000      15.900000          1.580000     1.000000   

       residual sugar    chlorides  free sulfur dioxide  total sulfur dioxide  \
count     1599.000000  1599.000000          1599.000000           1599.000000   
mean         2.538806     0.087467            15.874922             46.467792   
std          1.409928     0.047065            10.460157             32.895324   
min          0.900000     0.012000             1.000000              6.000000   
25%          1.900000     0.070000             7.000000             22.000000   
50%          2.200000     0.079000            14.000000             38.000000   
75%          2.600000     0.090000            21.000000             62.000000   
max         15.500000     0.611000            72.000000            289.000000   

           density           pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  1599.000000  
mean      0.996747     3.311113     0.658149    10.422983     5.636023  
std       0.001887     0.154386     0.169507     1.065668     0.807569  
min       0.990070     2.740000     0.330000     8.400000     3.000000  
25%       0.995600     3.210000     0.550000     9.500000     5.000000  
50%       0.996750     3.310000     0.620000    10.200000     6.000000  
75%       0.997835     3.400000     0.730000    11.100000     6.000000  
max       1.003690     4.010000     2.000000    14.900000     8.000000

In [89]:
y = data.quality
X = data.drop('quality', axis = 1)

In [90]:
X 

Wine_ID  fixed acidity  volatile acidity  citric acid  residual sugar  \
0           0            7.4             0.700         0.00             1.9   
1           1            7.8             0.880         0.00             2.6   
2           2            7.8             0.760         0.04             2.3   
3           3           11.2             0.280         0.56             1.9   
4           4            7.4             0.700         0.00             1.9   
5           5            7.4             0.660         0.00             1.8   
6           6            7.9             0.600         0.06             1.6   
7           7            7.3             0.650         0.00             1.2   
8           8            7.8             0.580         0.02             2.0   
9           9            7.5             0.500         0.36             6.1   
10         10            6.7             0.580         0.08             1.8   
11         11            7.5             0.500         0.36             6.1   
12         12            5.6             0.615         0.00             1.6   
13         13            7.8             0.610         0.29             1.6   
14         14            8.9             0.620         0.18             3.8   
15         15            8.9             0.620         0.19             3.9   
16         16            8.5             0.280         0.56             1.8   
17         17            8.1             0.560         0.28             1.7   
18         18            7.4             0.590         0.08             4.4   
19         19            7.9             0.320         0.51             1.8   
20         20            8.9             0.220         0.48             1.8   
21         21            7.6             0.390         0.31             2.3   
22         22            7.9             0.430         0.21             1.6   
23         23            8.5             0.490         0.11             2.3   
24         24            6.9             0.400         0.14             2.4   
25         25            6.3             0.390         0.16             1.4   
26         26            7.6             0.410         0.24             1.8   
27         27            7.9             0.430         0.21             1.6   
28         28            7.1             0.710         0.00             1.9   
29         29            7.8             0.645         0.00             2.0   
...       ...            ...               ...          ...             ...   
1569     1569            6.2             0.510         0.14             1.9   
1570     1570            6.4             0.360         0.53             2.2   
1571     1571            6.4             0.380         0.14             2.2   
1572     1572            7.3             0.690         0.32             2.2   
1573     1573            6.0             0.580         0.20             2.4   
1574     1574            5.6             0.310         0.78            13.9   
1575     1575            7.5             0.520         0.40             2.2   
1576     1576            8.0             0.300         0.63             1.6   
1577     1577            6.2             0.700         0.15             5.1   
1578     1578            6.8             0.670         0.15             1.8   
1579     1579            6.2             0.560         0.09             1.7   
1580     1580            7.4             0.350         0.33             2.4   
1581     1581            6.2             0.560         0.09             1.7   
1582     1582            6.1             0.715         0.10             2.6   
1583     1583            6.2             0.460         0.29             2.1   
1584     1584            6.7             0.320         0.44             2.4   
1585     1585            7.2             0.390         0.44             2.6   
1586     1586            7.5             0.310         0.41             2.4   
1587     1587            5.8             0.610         0

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, random_state=123, 
                                                    stratify=y)

In [92]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [93]:
X_train_scaled = scaler.transform(X_train)

In [94]:
X_train_scaled.mean(axis=0)

array([-2.22218213e-17,  1.16664562e-16, -3.05550043e-17, -8.47206937e-17,
       -2.22218213e-17,  2.22218213e-17, -6.38877362e-17, -4.16659149e-18,
       -2.54439854e-15, -8.70817622e-16, -4.08325966e-16, -1.87218844e-15])

In [95]:
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [96]:
X_test_scaled = scaler.transform(X_test)

In [97]:
X_test_scaled.mean(axis=0)

array([ 0.03159378,  0.02776704,  0.02592492, -0.03078587, -0.03137977,
       -0.00471876, -0.04413827, -0.02414174, -0.00293273, -0.00467444,
       -0.10894663,  0.01043391])

In [98]:
X_test_scaled.std(axis=0)

array([0.96964807, 1.02160495, 1.00135689, 0.97456598, 0.91099054,
       0.86716698, 0.94193125, 1.03673213, 1.03145119, 0.95734849,
       0.83829505, 1.0286218 ])

In [99]:
pipeline = make_pipeline(preprocessing.StandardScaler(),
                        RandomForestRegressor(n_estimators=100))

In [100]:
hyperparameters = { 'randomforestregressor__max_features' : ['auto', 'sqrt', 'log2'],
                  'randomforestregressor__max_depth': [None, 5, 3, 1]}

In [101]:
#Cross Validation Pipelining
clf = GridSearchCV(pipeline, hyperparameters, cv=12)
clf.fit(X_train, y_train)

GridSearchCV(cv=12, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decr...mators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'], 'randomforestregressor__max_depth': [None, 5, 3, 1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [102]:
clf.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'log2'}

In [103]:
clf.refit

True

In [104]:
y_pred = clf.predict(X_test)

In [105]:
r2_score(y_test, y_pred)

0.4778512016465889

In [106]:
mean_squared_error(y_test, y_pred)

0.33692875

In [107]:
joblib.dump(clf, 'rand_forest.pkl')

['rand_forest.pkl']

In [108]:
clf

GridSearchCV(cv=12, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decr...mators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'], 'randomforestregressor__max_depth': [None, 5, 3, 1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [109]:
y_pred

array([6.43, 5.74, 4.93, 5.44, 6.39, 5.53, 5.06, 4.87, 4.98, 5.95, 5.37,
       5.62, 5.93, 5.05, 5.83, 5.51, 6.67, 5.85, 5.78, 6.96, 5.53, 5.6 ,
       5.02, 6.  , 5.94, 5.03, 5.4 , 5.11, 5.92, 6.05, 5.92, 6.55, 6.  ,
       5.11, 5.11, 5.9 , 5.09, 6.1 , 5.12, 5.8 , 5.07, 5.81, 6.72, 5.13,
       6.24, 5.4 , 5.45, 5.55, 5.09, 6.52, 6.14, 5.3 , 5.73, 5.12, 5.47,
       5.68, 5.37, 5.37, 4.94, 5.25, 5.41, 5.19, 5.05, 5.82, 6.12, 5.29,
       6.38, 5.07, 5.25, 6.75, 5.8 , 5.73, 5.11, 5.05, 5.3 , 6.01, 5.37,
       5.14, 5.28, 5.37, 6.42, 5.63, 6.08, 6.4 , 5.08, 6.04, 6.47, 6.35,
       5.75, 5.91, 5.97, 5.31, 6.44, 5.62, 5.66, 5.83, 6.79, 6.76, 5.55,
       6.84, 5.11, 5.43, 5.14, 6.36, 5.02, 4.98, 5.6 , 4.97, 5.71, 5.96,
       5.96, 5.49, 6.03, 5.37, 5.  , 5.37, 5.85, 5.11, 5.12, 6.07, 5.87,
       5.13, 5.84, 6.23, 5.37, 5.24, 5.3 , 5.98, 5.56, 5.32, 5.91, 6.08,
       5.2 , 5.35, 5.06, 6.54, 5.  , 5.23, 6.71, 5.56, 5.22, 5.06, 5.52,
       6.14, 5.15, 5.44, 5.16, 6.55, 6.03, 5.07, 5.

In [118]:
submission = pd.DataFrame({"Wine_ID": X_test["Wine_ID"], "Quality": y_pred})
submission.to_csv("results.csv", index=False)

In [134]:
#converting the numpy array to list
x=np.array(y_pred).tolist()

#printing first 5 predictions
print("\nThe prediction:\n")
for i in range(0,5):
    print (x[i])
    
#printing first five expectations
print("\nThe expectation:\n")
print (y_test.head())


The prediction:

6.43
5.74
4.93
5.44
6.39

The expectation:

797     7
871     5
1333    5
1463    6
1058    7
Name: quality, dtype: int64


In [129]:
y_test.shape

(320,)

In [115]:
X_test.shape

(320, 12)